title: Ocre Docs
description: Documentation for the Ocre runtime
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: project-ocre/project-ocre.github.io
theme: just-the-docs

### General
# Serve site from docs
source: docs
destination: _site
favicon_ico: "/assets/images/favicon.png"
logo: "/assets/images/logo.png"
# Misc
heading_anchors: true
enable_copy_code_button: true
permalink: pretty

### Defaults paths/content types
defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

### Exclude files from build
exclude:
  - .DS_Store
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - package-lock.json

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# Callout config
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

### Sidebar
nav_external_links:
  - title: Ocre Docs on GitHub
    url: https://github.com/project-ocre/project-ocre.github.io

### Header
aux_links:
  "Ocre Docs on GitHub":
    - "https://github.com/project-ocre/project-ocre.github.io"

### Footer
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Copyright/license stuff
footer_content: 'Copyright &copy; 2024 Contributors to Project Ocre, which has been established as <a href="https://lfedge.org/projects/ocre"> Project Ocre a Series of LF Projects</a>, LLC. Distributed by an <a href="https://github.com/project-ocre/project-ocre.github.io/blob/main/LICENSE.txt">Apache 2.0 License.</a>'

#"Edit this page on GitHub" link text
#gh_edit_link: true # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub"
#gh_edit_repository: "https://github.com/project-ocre/project-ocre.github.io" # the github URL for your repo
#gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
#gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
